package com.freightos.fms.adapter.in.web.seahouse.dto;

import com.freightos.fms.application.seahouse.projection.SeaHouseListItem;
import com.freightos.common.util.Nullables;

import java.math.BigDecimal;

/** Sea House B/L 리스트 화면용 요약 DTO */
public record SeaHouseSummaryResponse(
        Long       id,
        String     hblNo,
        String     bound,
        String     mblNo,
        String     shipmentType,
        String     etd,
        String     eta,
        BigDecimal grossWeightKg,
        BigDecimal rton,
        Integer    pkgQty,
        String     pkgUnit,
        String     polCode,
        String     podCode,
        String     shipperCode,
        String     shipperName,
        String     consigneeCode,
        String     consigneeName,
        String     notifyCode,
        String     notifyName,
        String     settlePartnerCode,
        String     settlePartnerName,
        String     docPartnerCode,
        String     docPartnerName,
        String     linerCode,
        String     linerName,
        String     masterRefNo,
        String     freightTerm,
        String     incoterms,
        String     actualCustomerCode,
        String     actualCustomerName,
        String     salesManCode,
        String     teamCode,
        String     loadType,
        BigDecimal cbm,
        String     deliveryCode,
        String     vesselName,
        String     voyageNo,
        Long       cntr20Qty,
        Long       cntr40Qty,
        BigDecimal teuQty
) {
    public static SeaHouseSummaryResponse from(SeaHouseListItem item) {
        BigDecimal teuQty = Nullables.mapOrNull(item.lengthFeetSum(), s -> BigDecimal.valueOf(s).divide(BigDecimal.valueOf(20)));
        return new SeaHouseSummaryResponse(
                item.id(),
                item.hblNo(),
                item.bound(),
                item.mblNo(),
                item.shipmentType(),
                item.etd(),
                item.eta(),
                item.grossWeightKg(),
                item.rton(),
                item.pkgQty(),
                item.pkgUnit(),
                item.polCode(),
                item.podCode(),
                item.shipperCode(),
                item.shipperName(),
                item.consigneeCode(),
                item.consigneeName(),
                item.notifyCode(),
                item.notifyName(),
                item.settlePartnerCode(),
                item.settlePartnerName(),
                item.docPartnerCode(),
                item.docPartnerName(),
                item.linerCode(),
                item.linerName(),
                item.masterRefNo(),
                item.freightTerm(),
                item.incoterms(),
                item.actualCustomerCode(),
                item.actualCustomerName(),
                item.salesManCode(),
                item.teamCode(),
                item.loadType(),
                item.cbm(),
                item.deliveryCode(),
                item.vesselName(),
                item.voyageNo(),
                item.cntr20Qty(),
                item.cntr40Qty(),
                teuQty
        );
    }
}
