package com.freightos.admin.common.response;

public enum MessageCode {
    SUCCESS("성공"),
    CODE_MASTER_CREATED("코드 그룹이 등록되었습니다."),
    CODE_MASTER_UPDATED("코드 그룹이 수정되었습니다."),
    CODE_MASTER_DELETED("코드 그룹이 삭제되었습니다."),
    CODE_MASTER_NOT_FOUND("코드 그룹을 찾을 수 없습니다."),
    CODE_MASTER_DUPLICATE_CODE("동일한 마스터 코드가 이미 존재합니다."),
    CODE_MASTER_HAS_DETAIL_CANNOT_DELETE("하위 코드 항목이 존재하여 코드 그룹을 삭제할 수 없습니다."),
    CODE_DETAIL_CREATED("코드 항목이 등록되었습니다."),
    CODE_DETAIL_UPDATED("코드 항목이 수정되었습니다."),
    CODE_DETAIL_DELETED("코드 항목이 삭제되었습니다."),
    CODE_DETAIL_NOT_FOUND("코드 항목을 찾을 수 없습니다."),
    CODE_DUPLICATE_DETAIL_VALUE("선택한 마스터에 동일한 코드 값이 이미 존재합니다."),
    USER_CREATED("사용자가 등록되었습니다."),
    USER_UPDATED("사용자가 수정되었습니다."),
    USER_DELETED("사용자가 삭제되었습니다."),
    USER_NOT_FOUND("사용자를 찾을 수 없습니다."),
    USER_DUPLICATE_USERNAME("동일한 사용자 ID가 이미 존재합니다."),
    USER_ALREADY_DELETED("이미 삭제된 사용자입니다."),
    USER_LAST_ADMIN("마지막 활성 관리자는 삭제·비활성화할 수 없습니다."),
    CUSTOMER_CREATED("고객이 등록되었습니다."),
    CUSTOMER_UPDATED("고객이 수정되었습니다."),
    CUSTOMER_DELETED("고객이 삭제되었습니다."),
    CUSTOMER_NOT_FOUND("고객을 찾을 수 없습니다."),
    CUSTOMER_DUPLICATE_CODE("동일한 고객 코드가 이미 존재합니다."),
    CUSTOMER_ALREADY_DELETED("이미 삭제된 고객입니다."),
    NOTICE_CREATED("공지사항이 등록되었습니다."),
    NOTICE_UPDATED("공지사항이 수정되었습니다."),
    NOTICE_DELETED("공지사항이 삭제되었습니다."),
    NOTICE_NOT_FOUND("공지사항을 찾을 수 없습니다."),
    NOTICE_ALREADY_DELETED("이미 삭제된 공지사항입니다."),
    AUTH_ME_OK("사용자 정보를 조회했습니다."),
    AUTH_LOGIN_OK("로그인되었습니다."),
    AUTH_REFRESH_OK("토큰이 갱신되었습니다."),
    AUTH_LOGOUT_OK("로그아웃되었습니다."),
    MODULE_CREATED("모듈이 등록되었습니다."),
    MODULE_UPDATED("모듈이 수정되었습니다."),
    MODULE_DELETED("모듈이 삭제되었습니다."),
    MODULE_NOT_FOUND("모듈을 찾을 수 없습니다."),
    MODULE_DUPLICATE_CODE("동일한 모듈 코드가 이미 존재합니다."),
    MODULE_HAS_MENU_CANNOT_DELETE("해당 모듈을 참조하는 메뉴가 존재하여 삭제할 수 없습니다."),
    ATTRIBUTE_DEFINITION_CREATED("속성 정의가 등록되었습니다."),
    ATTRIBUTE_DEFINITION_UPDATED("속성 정의가 수정되었습니다."),
    ATTRIBUTE_DEFINITION_DELETED("속성 정의가 삭제되었습니다."),
    ATTRIBUTE_DEFINITION_NOT_FOUND("속성 정의를 찾을 수 없습니다."),
    ATTRIBUTE_DEFINITION_DUPLICATE_KEY("동일한 속성 키가 이미 존재합니다."),
    ATTRIBUTE_DEFINITION_IN_USE_CANNOT_DELETE("해당 속성 정의를 참조하는 데이터가 존재하여 삭제할 수 없습니다."),
    ATTRIBUTE_VALUE_CREATED("속성 값이 등록되었습니다."),
    ATTRIBUTE_VALUE_UPDATED("속성 값이 수정되었습니다."),
    ATTRIBUTE_VALUE_DELETED("속성 값이 삭제되었습니다."),
    ATTRIBUTE_VALUE_NOT_FOUND("속성 값을 찾을 수 없습니다."),
    ATTRIBUTE_VALUE_DUPLICATE("선택한 속성에 동일한 값이 이미 존재합니다."),
    ATTRIBUTE_VALUE_TYPE_NOT_ENUM("value_type이 ENUM인 속성 정의에만 속성 값을 등록할 수 있습니다."),
    MENU_CREATED("메뉴가 등록되었습니다."),
    MENU_UPDATED("메뉴가 수정되었습니다."),
    MENU_DELETED("메뉴가 삭제되었습니다."),
    MENU_NOT_FOUND("메뉴를 찾을 수 없습니다."),
    MENU_DUPLICATE_CODE("동일한 메뉴 코드가 이미 존재합니다."),
    MENU_HAS_CHILDREN_OR_BUTTONS_CANNOT_DELETE("하위 메뉴·버튼·정책이 존재하여 삭제할 수 없습니다."),
    MENU_PARENT_NOT_FOUND("상위 메뉴를 찾을 수 없습니다."),
    MENU_MODULE_NOT_FOUND("지정한 모듈을 찾을 수 없습니다."),
    BUTTON_CREATED("버튼이 등록되었습니다."),
    BUTTON_UPDATED("버튼이 수정되었습니다."),
    BUTTON_DELETED("버튼이 삭제되었습니다."),
    BUTTON_NOT_FOUND("버튼을 찾을 수 없습니다."),
    BUTTON_DUPLICATE_CODE("동일한 버튼 코드가 이미 존재합니다."),
    BUTTON_HAS_POLICY_CANNOT_DELETE("버튼 정책이 존재하여 삭제할 수 없습니다."),
    BUTTON_MENU_NOT_FOUND("지정한 메뉴를 찾을 수 없습니다."),
    MENU_POLICY_CREATED("메뉴 정책이 등록되었습니다."),
    MENU_POLICY_DELETED("메뉴 정책이 삭제되었습니다."),
    MENU_POLICY_NOT_FOUND("메뉴 정책을 찾을 수 없습니다."),
    MENU_POLICY_DUPLICATE("동일한 조합의 메뉴 정책이 이미 존재합니다."),
    BUTTON_POLICY_CREATED("버튼 정책이 등록되었습니다."),
    BUTTON_POLICY_DELETED("버튼 정책이 삭제되었습니다."),
    BUTTON_POLICY_NOT_FOUND("버튼 정책을 찾을 수 없습니다."),
    BUTTON_POLICY_DUPLICATE("동일한 조합의 버튼 정책이 이미 존재합니다."),
    FREIGHT_CREATED("운임이 등록되었습니다."),
    FREIGHT_UPDATED("운임이 수정되었습니다."),
    FREIGHT_DELETED("운임이 삭제되었습니다."),
    FREIGHT_NOT_FOUND("운임을 찾을 수 없습니다."),
    FREIGHT_DUPLICATE_CODE("동일한 운임 코드가 이미 존재합니다."),
    FREIGHT_ALREADY_DELETED("이미 삭제된 운임입니다."),
    CURRENCY_CREATED("통화가 등록되었습니다."),
    CURRENCY_UPDATED("통화가 수정되었습니다."),
    CURRENCY_DELETED("통화가 삭제되었습니다."),
    CURRENCY_NOT_FOUND("통화를 찾을 수 없습니다."),
    CURRENCY_DUPLICATE_CODE("동일한 통화 코드가 이미 존재합니다."),
    CURRENCY_ALREADY_DELETED("이미 삭제된 통화입니다."),
    EXCHANGE_RATE_CREATED("환율이 등록되었습니다."),
    EXCHANGE_RATE_UPDATED("환율이 수정되었습니다."),
    EXCHANGE_RATE_DELETED("환율이 삭제되었습니다."),
    EXCHANGE_RATE_NOT_FOUND("환율을 찾을 수 없습니다."),
    EXCHANGE_RATE_DUPLICATE_CODE("동일한 통화쌍의 환율이 이미 존재합니다."),
    EXCHANGE_RATE_ALREADY_DELETED("이미 삭제된 환율입니다."),
    PACKAGE_UNIT_CREATED("포장단위가 등록되었습니다."),
    PACKAGE_UNIT_UPDATED("포장단위가 수정되었습니다."),
    PACKAGE_UNIT_DELETED("포장단위가 삭제되었습니다."),
    PACKAGE_UNIT_NOT_FOUND("포장단위를 찾을 수 없습니다."),
    PACKAGE_UNIT_DUPLICATE_CODE("동일한 포장단위 코드가 이미 존재합니다."),
    PACKAGE_UNIT_ALREADY_DELETED("이미 삭제된 포장단위입니다."),
    HS_CODE_CREATED("HS Code가 등록되었습니다."),
    HS_CODE_UPDATED("HS Code가 수정되었습니다."),
    HS_CODE_DELETED("HS Code가 삭제되었습니다."),
    HS_CODE_NOT_FOUND("HS Code를 찾을 수 없습니다."),
    HS_CODE_DUPLICATE_CODE("동일한 HS Code가 이미 존재합니다."),
    HS_CODE_ALREADY_DELETED("이미 삭제된 HS Code입니다."),
    CARRIER_CREATED("선사가 등록되었습니다."),
    CARRIER_UPDATED("선사가 수정되었습니다."),
    CARRIER_DELETED("선사가 삭제되었습니다."),
    CARRIER_NOT_FOUND("선사를 찾을 수 없습니다."),
    CARRIER_DUPLICATE_CODE("동일한 선사 코드가 이미 존재합니다."),
    CARRIER_ALREADY_DELETED("이미 삭제된 선사입니다."),
    PORT_CREATED("항구가 등록되었습니다."),
    PORT_UPDATED("항구가 수정되었습니다."),
    PORT_DELETED("항구가 삭제되었습니다."),
    PORT_NOT_FOUND("항구를 찾을 수 없습니다."),
    PORT_DUPLICATE_CODE("동일한 항구 코드가 이미 존재합니다."),
    PORT_ALREADY_DELETED("이미 삭제된 항구입니다."),
    COUNTRY_CREATED("국가가 등록되었습니다."),
    COUNTRY_UPDATED("국가가 수정되었습니다."),
    COUNTRY_DELETED("국가가 삭제되었습니다."),
    COUNTRY_NOT_FOUND("국가를 찾을 수 없습니다."),
    COUNTRY_DUPLICATE_CODE("동일한 국가 코드가 이미 존재합니다."),
    COUNTRY_ALREADY_DELETED("이미 삭제된 국가입니다.");

    private final String message;

    MessageCode(String message) { this.message = message; }

    public String getMessage() { return message; }
}
