package com.freightos.admin.common.response;

public enum MessageCode {
    SUCCESS("성공"),
    CODE_MASTER_CREATED("코드 그룹이 등록되었습니다."),
    CODE_MASTER_UPDATED("코드 그룹이 수정되었습니다."),
    CODE_MASTER_DELETED("코드 그룹이 삭제되었습니다."),
    CODE_MASTER_NOT_FOUND("코드 그룹을 찾을 수 없습니다."),
    CODE_MASTER_DUPLICATE_CODE("동일한 master_code 코드 그룹이 이미 존재합니다."),
    CODE_MASTER_HAS_DETAIL_CANNOT_DELETE("하위 코드 항목이 존재하여 코드 그룹을 삭제할 수 없습니다."),
    CODE_DETAIL_CREATED("코드 항목이 등록되었습니다."),
    CODE_DETAIL_UPDATED("코드 항목이 수정되었습니다."),
    CODE_DETAIL_DELETED("코드 항목이 삭제되었습니다."),
    CODE_DETAIL_NOT_FOUND("코드 항목을 찾을 수 없습니다."),
    CODE_DUPLICATE_DETAIL_VALUE("동일한 master_id·code_value 코드 항목이 이미 존재합니다."),
    USER_CREATED("사용자가 등록되었습니다."),
    USER_UPDATED("사용자가 수정되었습니다."),
    USER_DELETED("사용자가 삭제되었습니다."),
    USER_NOT_FOUND("사용자를 찾을 수 없습니다."),
    USER_DUPLICATE_USERNAME("동일한 username 사용자가 이미 존재합니다."),
    USER_ALREADY_DELETED("이미 삭제된 사용자입니다."),
    USER_LAST_ADMIN("마지막 활성 관리자는 삭제·비활성화할 수 없습니다."),
    CUSTOMER_CREATED("고객이 등록되었습니다."),
    CUSTOMER_UPDATED("고객이 수정되었습니다."),
    CUSTOMER_DELETED("고객이 삭제되었습니다."),
    CUSTOMER_NOT_FOUND("고객을 찾을 수 없습니다."),
    CUSTOMER_DUPLICATE_CODE("동일한 customer_code 고객이 이미 존재합니다."),
    CUSTOMER_ALREADY_DELETED("이미 삭제된 고객입니다."),
    NOTICE_CREATED("공지사항이 등록되었습니다."),
    NOTICE_UPDATED("공지사항이 수정되었습니다."),
    NOTICE_DELETED("공지사항이 삭제되었습니다."),
    NOTICE_NOT_FOUND("공지사항을 찾을 수 없습니다."),
    NOTICE_ALREADY_DELETED("이미 삭제된 공지사항입니다."),
    TERMS_CREATED("약관이 등록되었습니다."),
    TERMS_UPDATED("약관이 수정되었습니다."),
    TERMS_DELETED("약관이 삭제되었습니다."),
    TERMS_NOT_FOUND("약관을 찾을 수 없습니다."),
    TERMS_ALREADY_DELETED("이미 삭제된 약관입니다."),
    FAQ_CATEGORY_CREATED("FAQ 카테고리가 등록되었습니다."),
    FAQ_CATEGORY_UPDATED("FAQ 카테고리가 수정되었습니다."),
    FAQ_CATEGORY_DELETED("FAQ 카테고리가 삭제되었습니다."),
    FAQ_CATEGORY_NOT_FOUND("FAQ 카테고리를 찾을 수 없습니다."),
    FAQ_CATEGORY_ALREADY_DELETED("이미 삭제된 FAQ 카테고리입니다."),
    FAQ_CREATED("FAQ가 등록되었습니다."),
    FAQ_UPDATED("FAQ가 수정되었습니다."),
    FAQ_DELETED("FAQ가 삭제되었습니다."),
    FAQ_NOT_FOUND("FAQ를 찾을 수 없습니다."),
    FAQ_ALREADY_DELETED("이미 삭제된 FAQ입니다."),
    AUTH_ME_OK("사용자 정보를 조회했습니다."),
    AUTH_LOGIN_OK("로그인되었습니다."),
    AUTH_REFRESH_OK("토큰이 갱신되었습니다."),
    AUTH_LOGOUT_OK("로그아웃되었습니다."),
    MODULE_CREATED("모듈이 등록되었습니다."),
    MODULE_UPDATED("모듈이 수정되었습니다."),
    MODULE_DELETED("모듈이 삭제되었습니다."),
    MODULE_NOT_FOUND("모듈을 찾을 수 없습니다."),
    MODULE_DUPLICATE_CODE("동일한 module_code 모듈이 이미 존재합니다."),
    MODULE_HAS_MENU_CANNOT_DELETE("해당 모듈을 참조하는 메뉴가 존재하여 삭제할 수 없습니다."),
    ATTRIBUTE_DEFINITION_CREATED("속성 정의가 등록되었습니다."),
    ATTRIBUTE_DEFINITION_UPDATED("속성 정의가 수정되었습니다."),
    ATTRIBUTE_DEFINITION_DELETED("속성 정의가 삭제되었습니다."),
    ATTRIBUTE_DEFINITION_NOT_FOUND("속성 정의를 찾을 수 없습니다."),
    ATTRIBUTE_DEFINITION_DUPLICATE_KEY("동일한 attribute_key 속성 정의가 이미 존재합니다."),
    ATTRIBUTE_DEFINITION_IN_USE_CANNOT_DELETE("해당 속성 정의를 참조하는 데이터가 존재하여 삭제할 수 없습니다."),
    ATTRIBUTE_VALUE_CREATED("속성 값이 등록되었습니다."),
    ATTRIBUTE_VALUE_UPDATED("속성 값이 수정되었습니다."),
    ATTRIBUTE_VALUE_DELETED("속성 값이 삭제되었습니다."),
    ATTRIBUTE_VALUE_NOT_FOUND("속성 값을 찾을 수 없습니다."),
    ATTRIBUTE_VALUE_DUPLICATE("동일한 attribute_key·value 속성 값이 이미 존재합니다."),
    ATTRIBUTE_VALUE_TYPE_NOT_ENUM("value_type이 ENUM인 속성 정의에만 속성 값을 등록할 수 있습니다."),
    MENU_CREATED("메뉴가 등록되었습니다."),
    MENU_UPDATED("메뉴가 수정되었습니다."),
    MENU_DELETED("메뉴가 삭제되었습니다."),
    MENU_NOT_FOUND("메뉴를 찾을 수 없습니다."),
    MENU_DUPLICATE_CODE("동일한 menu_code 메뉴가 이미 존재합니다."),
    MENU_HAS_CHILDREN_OR_BUTTONS_CANNOT_DELETE("하위 메뉴·버튼·정책이 존재하여 삭제할 수 없습니다."),
    MENU_PARENT_NOT_FOUND("상위 메뉴를 찾을 수 없습니다."),
    MENU_MODULE_NOT_FOUND("지정한 모듈을 찾을 수 없습니다."),
    BUTTON_CREATED("버튼이 등록되었습니다."),
    BUTTON_UPDATED("버튼이 수정되었습니다."),
    BUTTON_DELETED("버튼이 삭제되었습니다."),
    BUTTON_NOT_FOUND("버튼을 찾을 수 없습니다."),
    BUTTON_DUPLICATE_CODE("동일한 button_code 버튼이 이미 존재합니다."),
    BUTTON_HAS_POLICY_CANNOT_DELETE("버튼 정책이 존재하여 삭제할 수 없습니다."),
    BUTTON_MENU_NOT_FOUND("지정한 메뉴를 찾을 수 없습니다."),
    MENU_POLICY_CREATED("메뉴 정책이 등록되었습니다."),
    MENU_POLICY_DELETED("메뉴 정책이 삭제되었습니다."),
    MENU_POLICY_NOT_FOUND("메뉴 정책을 찾을 수 없습니다."),
    MENU_POLICY_DUPLICATE("동일한 조합의 메뉴 정책이 이미 존재합니다."),
    BUTTON_POLICY_CREATED("버튼 정책이 등록되었습니다."),
    BUTTON_POLICY_DELETED("버튼 정책이 삭제되었습니다."),
    BUTTON_POLICY_NOT_FOUND("버튼 정책을 찾을 수 없습니다."),
    BUTTON_POLICY_DUPLICATE("동일한 조합의 버튼 정책이 이미 존재합니다.");

    private final String message;

    MessageCode(String message) { this.message = message; }

    public String getMessage() { return message; }
}
