import type { HouseBlDetail, HouseBlAirScheduleLegView, HouseBlAirChargeView, HouseBlAirDimView, FreightLineView } from "@/domain/house-bl";
import { createEmptyHouseBlFormValues } from "./house-bl-defaults";
import type { HouseBlFormValues, FreightRow } from "./house-bl-schema";

/** FreightLineView(BE 응답) → FreightRow(form 값) 변환. 계산값도 string으로 보존. */
function mapFreightLine(l: FreightLineView): FreightRow {
  return {
    id:                  l.id,
    // RHF useFieldArray가 id를 UUID로 덮으므로 freight_line_id를 별도 필드에 보존
    freightLineId:       l.id,
    freightCode:         l.freightCode  ?? "",
    freightName:         l.freightName  ?? "",
    per:                 l.per          ?? "",
    qty:                 l.qty          != null ? String(l.qty)             : "",
    price:               l.price        != null ? String(l.price)           : "",
    currency:            l.currency     ?? "",
    exchangeRate:        l.exchangeRate != null ? String(l.exchangeRate)    : "",
    customerCode:        l.customerCode ?? "",
    customerName:        l.customerName ?? "",
    taxType:             l.taxType      ?? "",
    performanceDt:       l.performanceDt ?? "",
    settleAmount:        l.settleAmount  != null ? String(l.settleAmount)  : "",
    localAmount:         l.localAmount   != null ? String(l.localAmount)   : "",
    vat:                 l.localTaxAmount != null ? String(l.localTaxAmount) : "", // BE localTaxAmount → FE vat
    usdExchangeRate:     l.usdExchangeRate != null ? String(l.usdExchangeRate) : "",
    usdAmount:           l.usdAmount     != null ? String(l.usdAmount)     : "",
    financialDocType:    l.financialDocType ?? "",
    taxNo:               l.taxNo              ?? "",
    slipNo:              l.slipNo             ?? "",
    financialDocumentNo: l.financialDocumentNo ?? "",
  };
}

/** BE detail 응답을 form 값으로 매핑. 본 함수 시그니처 변경 시 form schema와 동시 정합 필수(§6.49 ⑧). */
export function mapHouseBlDetailToForm(detail: HouseBlDetail): HouseBlFormValues {
  return {
    ...createEmptyHouseBlFormValues(),
    // toolbar
    hbl:         detail.hblNo ?? "",
    mbl:         detail.mblNo ?? "",
    masterRefNo: detail.masterRefNo ?? "",
    masterBlId:  detail.masterBlId != null ? String(detail.masterBlId) : "",
    sType:       detail.shipmentType ?? "",
    lType:       detail.loadType ?? "",
    etd:         detail.etd ?? "",
    eta:         detail.eta ?? "",
    pol:         detail.polCode ?? "",
    pod:         detail.podCode ?? "",
    freightTerm: (detail.freightTerm ?? "") as "" | "PREPAID" | "COLLECT",
    expImp:      detail.bound,
    // party
    shipperCode:        detail.shipperCode    ?? "",
    shipperName:        detail.shipperName    ?? "",
    shipperAddress:     detail.shipperAddress ?? "",
    consigneeCode:      detail.consigneeCode  ?? "",
    consigneeName:      detail.consigneeName  ?? "",
    consigneeAddress:   detail.consigneeAddress ?? "",
    notifyCode:         detail.notifyCode     ?? "",
    notifyName:         detail.notifyName     ?? "",
    notifyAddress:      detail.notifyAddress  ?? "",
    docPartnerCode:     detail.docPartnerCode ?? "",
    docPartnerName:     detail.docPartnerName ?? "",
    docPartnerAddress:  detail.docPartnerAddress ?? "",
    // cargo summary
    pkgQty:          detail.pkgQty    != null ? String(detail.pkgQty)    : "",
    pkgUnit:         detail.pkgUnit   ?? "",
    weightUnit:      detail.weightUnit ?? "",
    grossWeightKg:   detail.grossWeightKg != null ? String(detail.grossWeightKg) : "",
    cbm:             detail.cbm        != null ? String(detail.cbm)        : "",
    volumeWeightKg:  detail.volumeWeightKg != null ? String(detail.volumeWeightKg) : "",
    // performance
    actualCustomerCode: detail.actualCustomerCode ?? "",
    actualCustomerName: detail.actualCustomerName ?? "",
    operatorCode:       detail.operatorCode  ?? "",
    operatorName:       detail.operatorName  ?? "",
    teamCode:           detail.teamCode      ?? "",
    teamName:           detail.teamName      ?? "",
    salesManCode:       detail.salesManCode  ?? "",
    salesManName:       detail.salesManName  ?? "",
    settlePartnerCode:  detail.settlePartnerCode ?? "",
    settlePartnerName:  detail.settlePartnerName ?? "",
    // schedule — linerCode/linerName은 toolbar 표시용 본체 필드
    // SEA: schedule-panel이 root linerName을 register하므로 seaDetail.linerName을 root에 매핑
    // Non-BL/TRUCK: root linerName 직접 사용
    linerCode:  detail.linerCode  ?? "",
    linerName:  detail.jobDiv === 'SEA'
      ? (detail.seaDetail?.linerName ?? "")
      : (detail.linerName ?? ""),
    // polName/podName: AIR는 root 필드(air-schedule-panel register), SEA는 seaDetail.polName 사용
    polName:    detail.polName    ?? "",
    podName:    detail.podName    ?? "",
    // trade
    incoterms:  detail.incoterms  ?? "",
    salesClass: detail.salesClass ?? "",
    hsCode:     detail.hsCode     ?? "",
    hsCodeName: detail.hsCodeName ?? "",
    // remark (본체 — SEA: HouseBlSea.remark, 화면: sea-remark-panel)
    remark: detail.remark ?? "",
    // SEA nested detail — BE Phase A-1에서 추가된 seaDetail 서브 엔티티 매핑
    seaDetail: {
      loadType:                detail.loadType                          ?? "",
      linerCode:               detail.seaDetail?.linerCode             ?? "",
      vesselCode:              detail.seaDetail?.vesselCode            ?? "",
      vesselName:              detail.seaDetail?.vesselName            ?? "",
      voyageNo:                detail.seaDetail?.voyageNo              ?? "",
      onboardDate:             detail.seaDetail?.onboardDate           ?? "",
      porCode:                 detail.seaDetail?.porCode               ?? "",
      finalDestCode:           detail.seaDetail?.finalDestCode         ?? "",
      issueDate:               detail.seaDetail?.issueDate             ?? "",
      noOfBl:                  detail.seaDetail?.noOfBl                ?? "",
      issuePlace:              detail.seaDetail?.issuePlace            ?? "",
      issuePlaceName:          detail.seaDetail?.issuePlaceName        ?? "",
      doDate:                  detail.seaDetail?.doDate                ?? "",
      payableAt:               detail.seaDetail?.payableAt             ?? "",
      payableAtName:           detail.seaDetail?.payableAtName         ?? "",
      triangle:                detail.seaDetail?.triangle              ?? false,
      serviceTerm:             detail.seaDetail?.serviceTerm           ?? "",
      vesselNationality:       detail.seaDetail?.vesselNationality     ?? "",
      rton:                    detail.seaDetail?.rton != null ? String(detail.seaDetail.rton) : "",
      sayInformation:          detail.seaDetail?.sayInformation        ?? "",
      noOfContainerOrPackages: detail.seaDetail?.noOfContainerOrPackages ?? "",
      blType:                  detail.blType                           ?? "",
      deliveryCode:            detail.deliveryCode                     ?? "",
      polName:                 detail.polName    ?? "",
      podName:                 detail.podName    ?? "",
      deliveryName:            detail.seaDetail?.deliveryName          ?? "",
      freightTermDetail:       "",
      signature:               "",
    },
    // §BE-sync — BE SeaDetailResponse.containers / .desc (seaDetail nested 경로)
    containers: detail.seaDetail?.containers?.map(c => ({
      id:            c.id,
      containerNo:   c.containerNo   ?? "",
      containerType: c.containerType ?? "",
      lengthFeet:    c.lengthFeet    != null ? String(c.lengthFeet)    : "",
      sealNo1:       c.sealNo1       ?? "",
      sealNo2:       c.sealNo2       ?? "",
      sealNo3:       c.sealNo3       ?? "",
      sealNo4:       c.sealNo4       ?? "",
      sealNo5:       c.sealNo5       ?? "",
      sealNo6:       c.sealNo6       ?? "",
      pkgQty:        c.pkgQty        != null ? String(c.pkgQty)        : "",
      pkgUnit:       c.pkgUnit       ?? "",
      grossWeightKg: c.grossWeightKg != null ? String(c.grossWeightKg) : "",
      netWeightKg:   c.netWeightKg   != null ? String(c.netWeightKg)   : "",
      cbm:           c.cbm           != null ? String(c.cbm)           : "",
      vgmKg:         c.vgmKg         != null ? String(c.vgmKg)         : "",
      soc:           c.soc           ?? false,
      seq:           c.seq           != null ? String(c.seq)           : "",
    })) ?? [],
    desc: {
      marks:        detail.airDetail?.desc?.marks       ?? detail.seaDetail?.desc?.marks       ?? "",
      description:  detail.airDetail?.desc?.description ?? detail.seaDetail?.desc?.description ?? "",
      descClause1:  detail.airDetail?.desc?.descClause1 ?? detail.seaDetail?.desc?.descClause1 ?? "",
      descClause2:  detail.airDetail?.desc?.descClause2 ?? detail.seaDetail?.desc?.descClause2 ?? "",
      // remark는 본체 필드 — desc에는 저장하지 않으므로 빈 문자열 유지
      remark:       "",
    },
    // AIR nested detail — BE Phase 2에서 추가된 airDetail 서브 엔티티 매핑 (§6.49 ⑯)
    // root에 산재되었던 airlineCode/airlineName/flightNo/flightDate → nested airDetail로 이전
    airDetail: {
      airlineCode:           detail.airDetail?.airlineCode            ?? "",
      airlineName:           "",
      chargeWeightKg:        detail.airDetail?.chargeWeightKg         != null ? String(detail.airDetail.chargeWeightKg) : "",
      volumeWeightKg:        detail.airDetail?.volumeWeightKg         != null ? String(detail.airDetail.volumeWeightKg) : "",
      rateClass:             detail.airDetail?.rateClass              ?? "",
      currencyCode:          detail.airDetail?.currencyCode           ?? "",
      declaredValueCarriage: detail.airDetail?.declaredValueCarriage  ?? "",
      declaredValueCustoms:  detail.airDetail?.declaredValueCustoms   ?? "",
      insurance:             detail.airDetail?.insurance              ?? "",
      accountInformation:    detail.airDetail?.accountInformation     ?? "",
      otherTerm:             detail.airDetail?.otherTerm              ?? "",
      issueDate:             detail.airDetail?.issueDate              ?? "",
      issuePlace:            detail.airDetail?.issuePlace             ?? "",
      signature:             detail.airDetail?.signature              ?? "",
      fhd:                   detail.airDetail?.fhd                   ?? "",
      handlingInformationCode: detail.airDetail?.handlingInformationCode ?? "",
      handlingInformationDesc: detail.airDetail?.handlingInformationDesc ?? "",
      originOfGoods:         detail.airDetail?.originOfGoods          ?? "",
      cargoType:             detail.airDetail?.cargoType              ?? "",
    },
    // §BE-sync — AirDetailResponse.scheduleLegs / .airCharges / .dims (airDetail nested 경로)
    scheduleLegs: detail.airDetail?.scheduleLegs?.map((s: HouseBlAirScheduleLegView) => ({
      id:        s.id,
      toCode:    s.toCode    ?? "",
      byCarrier: s.byCarrier ?? "",
      flightNo:  s.flightNo  ?? "",
      onBoardDt: s.onBoardDt ?? "",
      onBoardTm: s.onBoardTm ?? "",
      arrivalDt: s.arrivalDt ?? "",
      arrivalTm: s.arrivalTm ?? "",
    })) ?? [],
    airCharges: detail.airDetail?.airCharges?.map((a: HouseBlAirChargeView) => ({
      id:             a.id,
      freightCode:    a.freightCode    ?? "",
      currencyCode:   a.currencyCode   ?? "",
      per:            a.per            ?? "",
      freightTerm:    a.freightTerm    ?? "",
      grossWeightKg:  a.grossWeightKg  != null ? String(a.grossWeightKg)  : "",
      rateClass:      a.rateClass      ?? "",
      chargeWeightKg: a.chargeWeightKg != null ? String(a.chargeWeightKg) : "",
      rate:           a.rate           != null ? String(a.rate)           : "",
    })) ?? [],
    dims: detail.airDetail?.dims?.map((d: HouseBlAirDimView) => ({
      id:             d.id,
      lengthCm:       d.lengthCm       != null ? String(d.lengthCm)       : "",
      widthCm:        d.widthCm        != null ? String(d.widthCm)        : "",
      heightCm:       d.heightCm       != null ? String(d.heightCm)       : "",
      quantity:       d.quantity       != null ? String(d.quantity)       : "",
      cbm:            d.cbm            != null ? String(d.cbm)            : "",
      volumeWeightKg: d.volumeWeightKg != null ? String(d.volumeWeightKg) : "",
    })) ?? [],
    // §A2 — Freight 탭: 환율 헤더 + 매출/매입 라인 + 계산값 바인딩
    sellRateDt:          detail.freight?.sellRateDt          ?? "",
    sellRateCurrencyCode: detail.freight?.sellRateCurrencyCode ?? "",
    sellRate:            detail.freight?.sellRate  != null ? String(detail.freight.sellRate)  : "",
    buyRateDt:           detail.freight?.buyRateDt           ?? "",
    buyRateCurrencyCode: detail.freight?.buyRateCurrencyCode  ?? "",
    buyRate:             detail.freight?.buyRate   != null ? String(detail.freight.buyRate)   : "",
    usdRateDt:           detail.freight?.usdRateDt           ?? "",
    usdRate:             detail.freight?.usdRate   != null ? String(detail.freight.usdRate)   : "",
    freightSelling: detail.freight?.selling?.map(mapFreightLine) ?? [],
    freightBuying:  detail.freight?.buying?.map(mapFreightLine)  ?? [],
  };
}
