-- V46: 코드 데이터 8화면의 CREATE/UPDATE/DELETE 버튼을 SAVE 단일 버튼으로 통일.

-- ========== 1. SAVE 버튼 8건 INSERT ==========

INSERT INTO admin.button (menu_id, button_code, label, action_type, sort_order)
VALUES
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_FREIGHT'),       'ADMIN_CODE_FREIGHT_SAVE',       'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_CURRENCY'),      'ADMIN_CODE_CURRENCY_SAVE',      'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_EXCHANGE_RATE'), 'ADMIN_CODE_EXCHANGE_RATE_SAVE', 'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_PACKAGE'),       'ADMIN_CODE_PACKAGE_SAVE',       'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_HSCODE'),        'ADMIN_CODE_HSCODE_SAVE',        'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_CARRIER'),       'ADMIN_CODE_CARRIER_SAVE',       'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_PORT'),          'ADMIN_CODE_PORT_SAVE',          'Save', 'CUSTOM', 12),
    ((SELECT menu_id FROM admin.menu WHERE menu_code = 'ADMIN_CODE_COUNTRY'),       'ADMIN_CODE_COUNTRY_SAVE',       'Save', 'CUSTOM', 12)
ON CONFLICT (button_code) DO NOTHING;

-- ========== 2. SAVE 버튼 policy 8건 INSERT ==========

INSERT INTO admin.button_policy (button_id, attribute_key, required_value)
SELECT button_id, 'module', 'ADMIN'
FROM admin.button
WHERE button_code IN (
    'ADMIN_CODE_FREIGHT_SAVE',
    'ADMIN_CODE_CURRENCY_SAVE',
    'ADMIN_CODE_EXCHANGE_RATE_SAVE',
    'ADMIN_CODE_PACKAGE_SAVE',
    'ADMIN_CODE_HSCODE_SAVE',
    'ADMIN_CODE_CARRIER_SAVE',
    'ADMIN_CODE_PORT_SAVE',
    'ADMIN_CODE_COUNTRY_SAVE'
)
ON CONFLICT (button_id, attribute_key, required_value) DO NOTHING;

-- ========== 3. 구 CREATE/UPDATE/DELETE button_policy 삭제 (FK 선행) ==========

DELETE FROM admin.button_policy
WHERE button_id IN (
    SELECT button_id FROM admin.button
    WHERE button_code IN (
        'ADMIN_CODE_FREIGHT_CREATE',    'ADMIN_CODE_FREIGHT_UPDATE',    'ADMIN_CODE_FREIGHT_DELETE',
        'ADMIN_CODE_CURRENCY_CREATE',   'ADMIN_CODE_CURRENCY_UPDATE',   'ADMIN_CODE_CURRENCY_DELETE',
        'ADMIN_CODE_EXCHANGE_RATE_CREATE', 'ADMIN_CODE_EXCHANGE_RATE_UPDATE', 'ADMIN_CODE_EXCHANGE_RATE_DELETE',
        'ADMIN_CODE_PACKAGE_CREATE',    'ADMIN_CODE_PACKAGE_UPDATE',    'ADMIN_CODE_PACKAGE_DELETE',
        'ADMIN_CODE_HSCODE_CREATE',     'ADMIN_CODE_HSCODE_UPDATE',     'ADMIN_CODE_HSCODE_DELETE',
        'ADMIN_CODE_CARRIER_CREATE',    'ADMIN_CODE_CARRIER_UPDATE',    'ADMIN_CODE_CARRIER_DELETE',
        'ADMIN_CODE_PORT_CREATE',       'ADMIN_CODE_PORT_UPDATE',       'ADMIN_CODE_PORT_DELETE',
        'ADMIN_CODE_COUNTRY_CREATE',    'ADMIN_CODE_COUNTRY_UPDATE',    'ADMIN_CODE_COUNTRY_DELETE'
    )
);

-- ========== 4. 구 CREATE/UPDATE/DELETE 버튼 24건 삭제 ==========

DELETE FROM admin.button
WHERE button_code IN (
    'ADMIN_CODE_FREIGHT_CREATE',    'ADMIN_CODE_FREIGHT_UPDATE',    'ADMIN_CODE_FREIGHT_DELETE',
    'ADMIN_CODE_CURRENCY_CREATE',   'ADMIN_CODE_CURRENCY_UPDATE',   'ADMIN_CODE_CURRENCY_DELETE',
    'ADMIN_CODE_EXCHANGE_RATE_CREATE', 'ADMIN_CODE_EXCHANGE_RATE_UPDATE', 'ADMIN_CODE_EXCHANGE_RATE_DELETE',
    'ADMIN_CODE_PACKAGE_CREATE',    'ADMIN_CODE_PACKAGE_UPDATE',    'ADMIN_CODE_PACKAGE_DELETE',
    'ADMIN_CODE_HSCODE_CREATE',     'ADMIN_CODE_HSCODE_UPDATE',     'ADMIN_CODE_HSCODE_DELETE',
    'ADMIN_CODE_CARRIER_CREATE',    'ADMIN_CODE_CARRIER_UPDATE',    'ADMIN_CODE_CARRIER_DELETE',
    'ADMIN_CODE_PORT_CREATE',       'ADMIN_CODE_PORT_UPDATE',       'ADMIN_CODE_PORT_DELETE',
    'ADMIN_CODE_COUNTRY_CREATE',    'ADMIN_CODE_COUNTRY_UPDATE',    'ADMIN_CODE_COUNTRY_DELETE'
);
