import type { NonBlDetail, NonBlFreightLineView } from "@/domain/non-bl";
import { createEmptyNonBlFormValues } from "./non-bl-defaults";
import type { NonBlFormValues } from "./non-bl-schema";
import type { FreightRow } from "@/components/fms/house-bl/house-bl-schema";

/** NonBlFreightLineView → FreightRow 변환 */
function mapFreightLine(l: NonBlFreightLineView): FreightRow {
  return {
    id:                  l.id,
    freightCode:         l.freightCode  ?? "",
    freightName:         l.freightName  ?? "",
    per:                 l.per          ?? "",
    qty:                 l.qty          != null ? String(l.qty)             : "",
    price:               l.price        != null ? String(l.price)           : "",
    currency:            l.currency     ?? "",
    exchangeRate:        l.exchangeRate != null ? String(l.exchangeRate)    : "",
    customerCode:        l.customerCode ?? "",
    customerName:        l.customerName ?? "",
    taxType:             l.taxType      ?? "",
    performanceDt:       l.performanceDt ?? "",
    settleAmount:        l.settleAmount  != null ? String(l.settleAmount)  : "",
    localAmount:         l.localAmount   != null ? String(l.localAmount)   : "",
    vat:                 l.localTaxAmount != null ? String(l.localTaxAmount) : "",
    usdExchangeRate:     l.usdExchangeRate != null ? String(l.usdExchangeRate) : "",
    usdAmount:           l.usdAmount     != null ? String(l.usdAmount)     : "",
    financialDocType:    l.financialDocType ?? "",
    taxNo:               l.taxNo              ?? "",
    slipNo:              l.slipNo             ?? "",
    financialDocumentNo: l.financialDocumentNo ?? "",
  };
}

export function mapNonBlDetailToFormValues(detail: NonBlDetail): NonBlFormValues {
  return {
    ...createEmptyNonBlFormValues(),
    nonBlNo:            detail.hblNo ?? "",
    workDiv:            detail.workDivision ?? "",
    bound:              detail.bound ?? "",
    refNo:              detail.originalBlRef ?? "",
    shipperCode:        detail.shipperCode ?? "",
    consigneeCode:      detail.consigneeCode ?? "",
    notifyCode:         detail.notifyCode ?? "",
    settlePartnerCode:  detail.settlePartnerCode ?? "",
    actualCustomerCode: detail.actualCustomerCode ?? "",
    linerCode:          detail.linerCode ?? "",
    linerName:          detail.linerName ?? "",
    vesselName:         detail.vesselName ?? "",
    voyNo:              detail.voyageNo ?? "",
    etd:                detail.etd ?? "",
    eta:                detail.eta ?? "",
    polCode:            detail.polCode ?? "",
    podCode:            detail.podCode ?? "",
    finalDestCode:      detail.finalDestCode ?? "",
    finalDestName:      detail.finalDestName ?? "",
    finalEta:           detail.finalEta ?? "",
    mainItem:           detail.mainItemName ?? "",
    hsCode:             detail.hsCode ?? "",
    hsCodeName:         detail.hsCodeName ?? "",
    cargoQty:           detail.pkgQty,
    pkgUnit:            detail.pkgUnit ?? "",
    weightUnit:         detail.weightUnit ?? "",
    grossWt:            detail.grossWeightKg,
    totalCbm:           detail.cbm,
    rton:               detail.rton,
    volWt:              detail.volumeWtKg,
    operatorCode:       detail.operatorCode ?? "",
    salesManCode:       detail.salesManCode ?? "",
    teamCode:           detail.teamCode ?? "",
    teamName:           detail.teamName ?? "",
    salesClass:         detail.salesClass ?? undefined,
    // BE 응답 volumeDivisor → form 필드 dimensionDivisor
    dimensionDivisor:   detail.volumeDivisor ?? "CM6000",
    remark:             detail.remark ?? "",
    containers: detail.containers.map((c, idx) => ({
      id:       c.id ?? idx,
      cno:      c.containerNo ?? "",
      contType: c.containerType ?? "",
      sealNo1:  c.sealNo1 ?? "",
      sealNo2:  c.sealNo2 ?? "",
      sealNo3:  c.sealNo3 ?? "",
      pkg:      c.pkgQty,
      pkgUnit:  c.pkgUnit ?? "",
      grossWt:  c.grossWeightKg,
      cbm:      c.cbm,
    })),
    dimensions: detail.dims.map((d, idx) => ({
      id:     d.id ?? idx,
      length: d.lengthCm != null ? String(d.lengthCm) : "",
      width:  d.widthCm  != null ? String(d.widthCm)  : "",
      height: d.heightCm != null ? String(d.heightCm) : "",
      qty:    d.quantity != null ? String(d.quantity)  : "",
      cbm:    d.cbm      != null ? String(d.cbm)      : "",
      volWt:  d.volumeWeightKg != null ? String(d.volumeWeightKg) : "",
    })),
    // §A2 — Freight 탭: 환율 헤더 + 매출/매입 라인 + 계산값 바인딩
    sellRateDt:          detail.freight?.sellRateDt           ?? "",
    sellRateCurrencyCode: detail.freight?.sellRateCurrencyCode ?? "",
    sellRate:            detail.freight?.sellRate  != null ? String(detail.freight.sellRate)  : "",
    buyRateDt:           detail.freight?.buyRateDt            ?? "",
    buyRateCurrencyCode: detail.freight?.buyRateCurrencyCode   ?? "",
    buyRate:             detail.freight?.buyRate   != null ? String(detail.freight.buyRate)   : "",
    usdRateDt:           detail.freight?.usdRateDt            ?? "",
    usdRate:             detail.freight?.usdRate   != null ? String(detail.freight.usdRate)   : "",
    freightSelling: detail.freight?.selling?.map(mapFreightLine) ?? [],
    freightBuying:  detail.freight?.buying?.map(mapFreightLine)  ?? [],
  };
}
