import { API_AUTH_PORT } from '@/adapter/out/api/auth';
import { API_AIR_HOUSE_PORT } from '@/adapter/out/api/air-house';
import { API_SEA_HOUSE_PORT } from '@/adapter/out/api/sea-house';
import { API_AIR_MASTER_PORT } from '@/adapter/out/api/air-master';
import { API_SEA_MASTER_PORT } from '@/adapter/out/api/sea-master';
import { API_HOUSE_BL_PORT } from '@/adapter/out/api/house-bl';
import { API_MASTER_BL_PORT } from '@/adapter/out/api/master-bl';
import { API_NON_BL_PORT } from '@/adapter/out/api/non-bl';
import { API_SWITCH_BL_PORT } from '@/adapter/out/api/switch-bl';
import { API_TRUCK_BL_PORT } from '@/adapter/out/api/truck-bl';
import { mockHouseBlPort } from '@/adapter/out/mock/house-bl';
import { mockMasterBlPort } from '@/adapter/out/mock/master-bl';
import { mockSwitchBlPort } from '@/adapter/out/mock/switch-bl';
import { API_CODE_MASTER_PORT } from '@/adapter/out/api/code-master';
import { API_CODE_DETAIL_PORT } from '@/adapter/out/api/code-detail';
import { API_USER_PORT } from '@/adapter/out/api/user';
import { API_CUSTOMER_PORT } from '@/adapter/out/api/customer';
import { API_NOTICE_PORT } from '@/adapter/out/api/notice';
import { API_MODULE_PORT } from '@/adapter/out/api/access/module';
import { API_ATTRIBUTE_PORT } from '@/adapter/out/api/access/attribute';
import { API_ATTRIBUTE_VALUE_PORT } from '@/adapter/out/api/access/attribute-value';
import { API_MENU_PORT } from '@/adapter/out/api/access/menu';
import { API_BUTTON_PORT } from '@/adapter/out/api/access/button';
import { API_MENU_POLICY_PORT } from '@/adapter/out/api/access/menu-policy';
import { API_BUTTON_POLICY_PORT } from '@/adapter/out/api/access/button-policy';

const useMock = process.env.NEXT_PUBLIC_USE_MOCK === 'true';

export const airHousePort = API_AIR_HOUSE_PORT;
export const seaHousePort = API_SEA_HOUSE_PORT;
export const airMasterPort = API_AIR_MASTER_PORT;
export const seaMasterPort = API_SEA_MASTER_PORT;
export const houseBlPort = useMock ? mockHouseBlPort : API_HOUSE_BL_PORT;
export const masterBlPort = useMock ? mockMasterBlPort : API_MASTER_BL_PORT;
export const nonBlPort = API_NON_BL_PORT;
export const switchBlPort = useMock ? mockSwitchBlPort : API_SWITCH_BL_PORT;
export const truckBlPort = API_TRUCK_BL_PORT;
export const codeMasterPort = API_CODE_MASTER_PORT;
export const codeDetailPort = API_CODE_DETAIL_PORT;
export const userPort = API_USER_PORT;
export const customerPort = API_CUSTOMER_PORT;
export const noticePort = API_NOTICE_PORT;
export const authPort = API_AUTH_PORT;
export const accessModulePort = API_MODULE_PORT;
export const accessAttributePort = API_ATTRIBUTE_PORT;
export const accessAttributeValuePort = API_ATTRIBUTE_VALUE_PORT;
export const accessMenuPort = API_MENU_PORT;
export const accessButtonPort = API_BUTTON_PORT;
export const accessMenuPolicyPort = API_MENU_POLICY_PORT;
export const accessButtonPolicyPort = API_BUTTON_POLICY_PORT;
