import { API_AUTH_PORT } from '@/adapter/out/api/auth';
import { API_AIR_HOUSE_PORT } from '@/adapter/out/api/air-house';
import { API_SEA_HOUSE_PORT } from '@/adapter/out/api/sea-house';
import { API_AIR_MASTER_PORT } from '@/adapter/out/api/air-master';
import { API_SEA_MASTER_PORT } from '@/adapter/out/api/sea-master';
import { API_HOUSE_BL_PORT } from '@/adapter/out/api/house-bl';
import { API_MASTER_BL_PORT } from '@/adapter/out/api/master-bl';
import { API_NON_BL_PORT } from '@/adapter/out/api/non-bl';
import { API_SWITCH_BL_PORT } from '@/adapter/out/api/switch-bl';
import { API_TRUCK_BL_PORT } from '@/adapter/out/api/truck-bl';
import { mockHouseBlPort } from '@/adapter/out/mock/house-bl';
import { mockMasterBlPort } from '@/adapter/out/mock/master-bl';
import { mockSwitchBlPort } from '@/adapter/out/mock/switch-bl';
import { API_CODE_MASTER_PORT } from '@/adapter/out/api/code-master';
import { API_CODE_DETAIL_PORT } from '@/adapter/out/api/code-detail';
import { API_USER_PORT } from '@/adapter/out/api/user';
import { API_CUSTOMER_PORT } from '@/adapter/out/api/customer';
import { API_FREIGHT_PORT } from '@/adapter/out/api/code/freight';
import { API_CARRIER_PORT } from '@/adapter/out/api/code/carrier';
import { API_PORT_PORT } from '@/adapter/out/api/code/port';
import { API_EXCHANGE_RATE_PORT } from '@/adapter/out/api/code/exchange-rate';
import { API_CURRENCY_PORT } from '@/adapter/out/api/code/currency';
import { API_PACKAGE_UNIT_PORT } from '@/adapter/out/api/code/package-unit';
import { API_HS_CODE_PORT } from '@/adapter/out/api/code/hs-code';
import { API_COUNTRY_PORT } from '@/adapter/out/api/code/country';
import { API_NOTICE_PORT } from '@/adapter/out/api/notice';
import { API_ATTRIBUTE_PORT } from '@/adapter/out/api/access/attribute';
import { API_ATTRIBUTE_VALUE_PORT } from '@/adapter/out/api/access/attribute-value';
import { API_MENU_PORT } from '@/adapter/out/api/access/menu';
import { API_BUTTON_PORT } from '@/adapter/out/api/access/button';
import { API_SIDEBAR_MENU_PORT } from '@/adapter/out/api/access/sidebar-menu';
import { API_PERMISSION_PRESET_PORT } from '@/adapter/out/api/access/permission-preset';
import { apiUserPermissionPresetPort } from '@/adapter/out/api/access/user-permission-preset';
import { API_TEAM_PORT } from '@/adapter/out/api/team';
import { API_SUBSCRIBER_PORT } from '@/adapter/out/api/subscriber';
import { API_SUBSCRIPTION_PORT } from '@/adapter/out/api/subscription';
import { API_UI_LAYOUT_PORT } from '@/adapter/out/api/ui-layout';
import { API_BL_QUICK_SEARCH_PORT } from '@/adapter/out/api/bl-quick-search';

const useMock = process.env.NEXT_PUBLIC_USE_MOCK === 'true';

export const airHousePort = API_AIR_HOUSE_PORT;
export const seaHousePort = API_SEA_HOUSE_PORT;
export const airMasterPort = API_AIR_MASTER_PORT;
export const seaMasterPort = API_SEA_MASTER_PORT;
export const houseBlPort = useMock ? mockHouseBlPort : API_HOUSE_BL_PORT;
export const masterBlPort = useMock ? mockMasterBlPort : API_MASTER_BL_PORT;
export const nonBlPort = API_NON_BL_PORT;
export const switchBlPort = useMock ? mockSwitchBlPort : API_SWITCH_BL_PORT;
export const truckBlPort = API_TRUCK_BL_PORT;
export const codeMasterPort = API_CODE_MASTER_PORT;
export const codeDetailPort = API_CODE_DETAIL_PORT;
export const userPort = API_USER_PORT;
export const customerPort = API_CUSTOMER_PORT;
export const freightPort = API_FREIGHT_PORT;
export const carrierPort = API_CARRIER_PORT;
export const portPort = API_PORT_PORT;
export const exchangeRatePort = API_EXCHANGE_RATE_PORT;
export const currencyPort = API_CURRENCY_PORT;
export const packageUnitPort = API_PACKAGE_UNIT_PORT;
export const hsCodePort = API_HS_CODE_PORT;
export const countryPort = API_COUNTRY_PORT;
export const noticePort = API_NOTICE_PORT;
export const authPort = API_AUTH_PORT;
export const accessAttributePort = API_ATTRIBUTE_PORT;
export const accessAttributeValuePort = API_ATTRIBUTE_VALUE_PORT;
export const accessMenuPort = API_MENU_PORT;
export const accessButtonPort = API_BUTTON_PORT;
export const sidebarMenuPort = API_SIDEBAR_MENU_PORT;
export const permissionPresetPort = API_PERMISSION_PRESET_PORT;
export const accessUserPermissionPresetPort = apiUserPermissionPresetPort;
export const teamPort = API_TEAM_PORT;
export const subscriberPort = API_SUBSCRIBER_PORT;
export const subscriptionPort = API_SUBSCRIPTION_PORT;
export const uiLayoutPort = API_UI_LAYOUT_PORT;
export const blQuickSearchPort = API_BL_QUICK_SEARCH_PORT;
