import type { MasterBlFormValues } from "./master-bl-schema";

/** Master B/L 신규 입력 시 form 기본값. Status 필드 미포함 (BE 미지원, 사용자 결정 2026-05-15). */
export function createEmptyMasterBlFormValues(): MasterBlFormValues {
  return {
    jobDiv: "SEA",
    bound: "EXP",
    freightTerm: undefined,
    mblNo: "",
    masterRefNo: "",
    shipperCode: "",
    shipperAddress: "",
    consigneeCode: "",
    consigneeAddress: "",
    notifyCode: "",
    notifyAddress: "",
    polCode: "",
    podCode: "",
    etd: "",
    eta: "",
    pkgUnit: "",
    weightUnit: "",
    hsCode: "",
    mainItemName: "",
    settlePartnerCode: "",
    operatorCode: "",
    shipmentType: "",
    rateClass: "",
    coLoadAgent: "",
    coLoadType: "",
    flightType: "",
    securityStatus: "",
    teamCode: "",
    remark: "",
    // §BE-sync — seaDetail nested 빈 객체 (15 필드, desc root 승격)
    seaDetail: {
      loadType: undefined,
      linerCode: undefined,
      vesselCode: undefined,
      vesselName: undefined,
      voyageNo: undefined,
      onboardDate: "",
      vesselNationality: undefined,
      serviceTerm: undefined,
      blType: undefined,
      porCode: undefined,
      finalDestCode: undefined,
      rton: undefined,
      lineBkgNo: undefined,
      issueDate: "",
      remark: undefined,
    },
    desc: {
      marks: "",
      description: "",
      descClause1: "",
      descClause2: "",
      remark: "",
    },
    dims: [],
    scheduleLegs: [],
    airCharges: [],
    houseBls: [],
    consoledSeaContainers: [],
  };
}
