import { z } from "zod";

// freightTerm 값이 null일 수 있으므로 detail reset 시 기본값 fallback 처리
export const MASTER_BL_SCHEMA = z.object({
  jobDiv: z.enum(["SEA", "AIR", "TRUCK", "NON_BL"]),
  bound: z.enum(["EXP", "IMP"]),
  mblNo: z.string().max(35).optional(),
  masterRefNo: z.string().max(35).optional(),
  freightTerm: z.enum(["PREPAID", "COLLECT"]),
  shipperCode: z.string().max(20).optional(),
  consigneeCode: z.string().max(20).optional(),
  polCode: z.string().max(5).optional(),
  podCode: z.string().max(5).optional(),
  etd: z.string().regex(/^\d{8}$/).optional().or(z.literal("")),
  eta: z.string().regex(/^\d{8}$/).optional().or(z.literal("")),
  pkgQty: z.number().min(0).optional(),
  grossWeightKg: z.number().min(0).optional(),
  cbm: z.number().min(0).optional(),
  operatorCode: z.string().optional(),
  shipmentType: z.string().optional(),
  mblStatus: z.string().optional(),
  cargoMainItem: z.string().optional(),
  cargoHsCode: z.string().optional(),
  rTon: z.number().min(0).optional(),
  volWeight: z.number().min(0).optional(),
  chargeWeight: z.number().min(0).optional(),
  rateClass: z.string().optional(),
  settlePartner: z.string().optional(),
  coLoadAgent: z.string().optional(),
  coLoadType: z.string().optional(),
  flightType: z.string().optional(),
  securityStatus: z.string().optional(),
  teamCode: z.string().optional(),
  seaDetail: z.object({
    lineBkgNo: z.string().optional(),
    loadType: z.string().optional(),
    serviceTerm: z.string().optional(),
    blType: z.string().optional(),
    linerCode: z.string().optional(),
    linerName: z.string().optional(),
    vesselName: z.string().optional(),
    voyageNo: z.string().optional(),
    issueDate: z.string().optional(),
    freightTermDetail: z.string().optional(),
    polName: z.string().optional(),
    podName: z.string().optional(),
    deliveryCode: z.string().optional(),
    deliveryName: z.string().optional(),
    signature: z.string().optional(),
    issuePlace: z.string().optional(),
  }).optional(),
});

export type MasterBlFormValues = z.infer<typeof MASTER_BL_SCHEMA>;

// toolbar 라벨 → RHF field path 매핑
export const TOOLBAR_TO_FIELD: Partial<Record<string, string>> = {
  "Master Ref":    "masterRefNo",
  "MBL No":        "mblNo",
  "MAWB No":       "mblNo",
  "Line Bkg. No":  "seaDetail.lineBkgNo",
  "Load Type":     "seaDetail.loadType",
  "Service Term":  "seaDetail.serviceTerm",
  "B/L Type":      "seaDetail.blType",
  "Shipment Type": "shipmentType",
  "Status":        "mblStatus",
};

export const MASTER_BL_DEFAULT_VALUES: MasterBlFormValues = {
  jobDiv: "SEA",
  bound: "EXP",
  freightTerm: "PREPAID",
  mblNo: "",
  masterRefNo: "",
  shipperCode: "",
  consigneeCode: "",
  polCode: "",
  podCode: "",
  etd: "",
  eta: "",
  operatorCode: "",
  shipmentType: "",
  mblStatus: "",
  cargoMainItem: "",
  cargoHsCode: "",
  rateClass: "",
  settlePartner: "",
  coLoadAgent: "",
  coLoadType: "",
  flightType: "",
  securityStatus: "",
  teamCode: "",
  seaDetail: {
    lineBkgNo: "",
    loadType: "",
    serviceTerm: "",
    blType: "",
    linerCode: "",
    linerName: "",
    vesselName: "",
    voyageNo: "",
    issueDate: "",
    freightTermDetail: "",
    polName: "",
    podName: "",
    deliveryCode: "",
    deliveryName: "",
    signature: "",
    issuePlace: "",
  },
};
